# -*- coding: utf-8 -*-

#File gui.py để thiết kế giao diện. Sử dụng thư viện PyQT5

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 1071, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(220, 290, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(778, 296, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_open = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_open.setGeometry(QtCore.QRect(485, 90, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setFlat(False)
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_Color_1 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_Color_1.setGeometry(QtCore.QRect(485, 140, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Color_1.setFont(font)
        self.pushButton_Color_1.setObjectName("pushButton_Color_1")
        self.label_anhgoc = QtWidgets.QLabel(self.tab_1)
        self.label_anhgoc.setGeometry(QtCore.QRect(20, 20, 451, 255))
        self.label_anhgoc.setAutoFillBackground(True)
        self.label_anhgoc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_anhgoc.setObjectName("label_anhgoc")
        self.label_anhmau = QtWidgets.QLabel(self.tab_1)
        self.label_anhmau.setGeometry(QtCore.QRect(599, 20, 451, 255))
        self.label_anhmau.setAutoFillBackground(True)
        self.label_anhmau.setAlignment(QtCore.Qt.AlignCenter)
        self.label_anhmau.setObjectName("label_anhmau")
        self.pushButton_Color_2 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_Color_2.setGeometry(QtCore.QRect(486, 190, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Color_2.setFont(font)
        self.pushButton_Color_2.setObjectName("pushButton_Color_2")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_videomau = QtWidgets.QLabel(self.tab_2)
        self.label_videomau.setGeometry(QtCore.QRect(593, 20, 451, 255))
        self.label_videomau.setAutoFillBackground(True)
        self.label_videomau.setAlignment(QtCore.Qt.AlignCenter)
        self.label_videomau.setObjectName("label_videomau")
        #self.pushButton_open_2 = QtWidgets.QPushButton(self.tab_2)
        #self.pushButton_open_2.setGeometry(QtCore.QRect(479, 90, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        #self.pushButton_open_2.setFont(font)
        #self.pushButton_open_2.setFlat(False)
        #self.pushButton_open_2.setObjectName("pushButton_open_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(772, 296, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_videogoc = QtWidgets.QLabel(self.tab_2)
        self.label_videogoc.setGeometry(QtCore.QRect(14, 20, 451, 255))
        self.label_videogoc.setAutoFillBackground(True)
        self.label_videogoc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_videogoc.setObjectName("label_videogoc")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(214, 290, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_Color_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Color_3.setGeometry(QtCore.QRect(479, 140, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Color_3.setFont(font)
        self.pushButton_Color_3.setObjectName("pushButton_Color_3")
        self.pushButton_Color_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Color_4.setGeometry(QtCore.QRect(480, 190, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Color_4.setFont(font)
        self.pushButton_Color_4.setObjectName("pushButton_Color_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuT_p = QtWidgets.QMenu(self.menuBar)
        self.menuT_p.setObjectName("menuT_p")
        self.menuGi_i_thi_u = QtWidgets.QMenu(self.menuBar)
        self.menuGi_i_thi_u.setObjectName("menuGi_i_thi_u")
        MainWindow.setMenuBar(self.menuBar)
        self.actionTho_t = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionTho_t.setFont(font)
        self.actionTho_t.setObjectName("actionTho_t")
        self.actionVer_1_0 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionVer_1_0.setFont(font)
        self.actionVer_1_0.setObjectName("actionVer_1_0")
        self.menuT_p.addAction(self.actionTho_t)
        self.menuGi_i_thi_u.addAction(self.actionVer_1_0)
        self.menuBar.addAction(self.menuT_p.menuAction())
        self.menuBar.addAction(self.menuGi_i_thi_u.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Màu hóa ảnh và video"))
        self.label.setText(_translate("MainWindow", "Ảnh gốc"))
        self.label_2.setText(_translate("MainWindow", "Ảnh màu hóa"))
        self.pushButton_open.setText(_translate("MainWindow", "Mở file"))
        self.pushButton_Color_1.setText(_translate("MainWindow", "Màu hóa 1"))
        self.label_anhgoc.setText(_translate("MainWindow", ""))
        self.label_anhmau.setText(_translate("MainWindow", ""))
        self.pushButton_Color_2.setText(_translate("MainWindow", "Màu hóa 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Màu hóa ảnh"))
        self.label_videomau.setText(_translate("MainWindow", ""))
        #self.pushButton_open_2.setText(_translate("MainWindow", "Mở file"))
        self.label_3.setText(_translate("MainWindow", "Video màu hóa"))
        self.label_videogoc.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "Video gốc"))
        self.pushButton_Color_3.setText(_translate("MainWindow", "Màu hóa 1"))
        self.pushButton_Color_4.setText(_translate("MainWindow", "Màu hóa 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Màu hóa video"))
        self.menuT_p.setTitle(_translate("MainWindow", "Tệp"))
        self.menuGi_i_thi_u.setTitle(_translate("MainWindow", "Giới thiệu"))
        self.actionTho_t.setText(_translate("MainWindow", "Thoát"))
        self.actionVer_1_0.setText(_translate("MainWindow", "Ver 1.0"))



        self.pushButton_open.clicked.connect(self.open)
        self.actionTho_t.triggered.connect(self.close)

        self.pushButton_Color_1.clicked.connect(self.mauhoa_anh1)
        self.pushButton_Color_2.clicked.connect(self.mauhoa_anh2)
        self.pushButton_Color_3.clicked.connect(self.mauhoa_video1)
        self.pushButton_Color_4.clicked.connect(self.mauhoa_video2)

        #self.pushButton_open_2.clicked.connect(self.open_video)